export enum LISTITEMSIZE {
  ITEMWIDTH = 500,
  ITEMHEIGHT = 500,
  CLOTHIMAGEWIDTH = 500,
  CLOTHIMAGEHEIGHT = 500,
  BRANDLOGOWIDTH = 400,
  BRANDLOGOHEIGHT = 200,
  COOPERLOGOWIDTH = 200,
  COOPERLOGOHEIGHT = 200,
}
export enum MAINITEMSIZE {
  MAINIMAGEWIDTH = 450,
  MAINIMAGEHEIGHT = 450,
  LOGOIMAGEWIDTH = 85,
  LOGOIMAGEHEIGHT = 85,
}
